source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'CQTextField_Example', :exclusive => true do
  pod "CQTextField", :path => "../"
end

target 'CQTextField_Tests', :exclusive => true do
  pod "CQTextField", :path => "../"

  
end
